#    ___  __  ____ ____ _____   ___  _  ________  __
#   / _ )/ / / / //_/ // / _ | / _ \/ |/ / __/\ \/ /
#  / _  / /_/ / ,< / _  / __ |/ , _/    / _/   \  /
# /____/\____/_/|_/_//_/_/ |_/_/|_/_/|_/___/   /_/
#
# Developed by: @Bukharney

services:
  myas_client:
    image: public.ecr.aws/z4n6o0v4/myas/client:latest
    container_name: myas_client
    expose:
      - 4173
    networks:
      - caddy_net

  myas_server:
    image: public.ecr.aws/z4n6o0v4/myas/server:latest
    container_name: myas_server
    expose:
      - 8080
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - AES_KEY=${AES_KEY}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ACCESS_TOKEN_EXPIRES_IN=${ACCESS_TOKEN_EXPIRES_IN}
      - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN}
      - VERIFICATION_EXPIRES_IN=${VERIFICATION_EXPIRES_IN}
    depends_on:
      myas_redis:
        condition: service_healthy
    networks:
      - caddy_net

  myas_redis:
    container_name: myas_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    environment:
      - REDIS_REQUIREPASS=${REDIS_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-h",
          "localhost",
          "-p",
          "6379",
          "-a",
          "${REDIS_PASSWORD}",
          "ping",
        ]
      interval: 5s
      timeout: 5s
      retries: 3
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
